name: Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # For pushing changes back
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }} # Checkout the PR branch if it's a PR, otherwise the commit branch

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run format # This script will be added to package.json

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git diff --staged --quiet || (git commit -m "Automated formatting" && git push)
