name: Suite

on:
  pull_request:
    branches:
      - dev
      - main

  schedule:
    - cron: '0 4 * * *' # Runs daily at 4 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: NodeJS environment setup
      uses: actions/setup-node@v4
      with:
        node-version: '18.x' # You can specify other versions

    - name: NodeJS dependency setup
      run: npm install

    - name: Test project source code
      run: npm test
